version: '3.8'

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app
    container_name: my-app_container
    restart: always
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_URLS=http://+:8082  # Set the application to listen on port 8082
      - KEYCLOAK__INTERNAL_HOST=http://keycloak:8080
      - KEYCLOAK__EXTERNAL_HOST=http://localhost:8081
    depends_on:
      - keycloak

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: keycloak
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak_container
    restart: always
    environment:
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: P@ssw0rd
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
